# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jen < Formula
  desc "Jen is a CLI tool for scaffolding new microservices based on Go templates, onboarding them with your CI/CD and infra, and augmenting them with your DevOps scripts for their entire life-time."
  homepage "https://github.com/silphid/jen"
  version "0.2.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silphid/jen/releases/download/v0.2.22/jen_0.2.22_darwin_amd64.tar.gz"
      sha256 "e970f613f060f6ca3a408c4d6fd18126017b4ed14627967e9ebc405a3975200a"

      def install
        bin.install "jen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silphid/jen/releases/download/v0.2.22/jen_0.2.22_darwin_arm64.tar.gz"
      sha256 "5eb280cb2490003652cd6a9d0d5c7644825c39df1b4ab59f549b2b126cf11a34"

      def install
        bin.install "jen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/silphid/jen/releases/download/v0.2.22/jen_0.2.22_linux_arm64.tar.gz"
      sha256 "e31109886bde340e0053f44fc4578cb0f5970a30f638689e80989b29779b8899"

      def install
        bin.install "jen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/silphid/jen/releases/download/v0.2.22/jen_0.2.22_linux_amd64.tar.gz"
      sha256 "395de790bc684bff7e2976172c0ec0e57476b3b304df4fbc1ff92ebf2766f9c2"

      def install
        bin.install "jen"
      end
    end
  end
end
