# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jen < Formula
  desc "Jen is a CLI tool for scaffolding new microservices based on Go templates, onboarding them with your CI/CD and infra, and augmenting them with your DevOps scripts for their entire life-time."
  homepage "https://github.com/silphid/jen"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silphid/jen/releases/download/v0.5.1/jen_0.5.1_darwin_amd64.tar.gz"
      sha256 "b19160b575156b48bf54e594597fdf48f50f8763d7a3fb59fc4c113971cd8498"

      def install
        bin.install "jen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silphid/jen/releases/download/v0.5.1/jen_0.5.1_darwin_arm64.tar.gz"
      sha256 "21bf381dc0a2438fc35f449f49a916f21783869612e9759bef684e3eed6fa4c2"

      def install
        bin.install "jen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/silphid/jen/releases/download/v0.5.1/jen_0.5.1_linux_amd64.tar.gz"
      sha256 "1696c11c0b713e04add5e6bb0f4d88d812922d30a60ea76b8386288b34039f28"
      def install
        bin.install "jen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/silphid/jen/releases/download/v0.5.1/jen_0.5.1_linux_arm64.tar.gz"
      sha256 "569f4fd63260ac7ee42e99a787353989888ffad4bd6896a5f45ac38ef499ddd5"
      def install
        bin.install "jen"
      end
    end
  end
end
