# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testchart < Formula
  desc "Helm chart unit testing CLI tool"
  homepage "https://github.com/silphid/testchart"
  version "0.0.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silphid/testchart/releases/download/v0.0.22/testchart_0.0.22_darwin_amd64.tar.gz"
      sha256 "720718a6b36fe93d85eb18c72b0d2f5ec2eecb1910b13a06171ceaf14ce564ce"

      def install
        bin.install "testchart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silphid/testchart/releases/download/v0.0.22/testchart_0.0.22_darwin_arm64.tar.gz"
      sha256 "ec50e55c699b28bbcb8331fa507dc2073008012ac0f00bda86322f8e9073ec35"

      def install
        bin.install "testchart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/silphid/testchart/releases/download/v0.0.22/testchart_0.0.22_linux_arm64.tar.gz"
      sha256 "ffcd31478100bb228f45ec3fca365989fa9a1ef027fd0482786e3674431378c8"

      def install
        bin.install "testchart"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/silphid/testchart/releases/download/v0.0.22/testchart_0.0.22_linux_amd64.tar.gz"
      sha256 "06fd434f85b31942ae632ed3d56b8288b233583abe1dbe692061233be333fafe"

      def install
        bin.install "testchart"
      end
    end
  end
end
