# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testchart < Formula
  desc "Helm chart unit testing CLI tool"
  homepage "https://github.com/silphid/testchart"
  version "0.0.44"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/silphid/testchart/releases/download/v0.0.44/testchart_0.0.44_darwin_amd64.tar.gz"
      sha256 "3040ae1655a67ef74e7d0969a9558fc570505c70190035b6618898a298da37d3"

      def install
        bin.install "testchart"
      end
    end
    on_arm do
      url "https://github.com/silphid/testchart/releases/download/v0.0.44/testchart_0.0.44_darwin_arm64.tar.gz"
      sha256 "9d1f2e6e99fb4ad47c53686f35a34c6259366a9674c885af21a34ca34150accf"

      def install
        bin.install "testchart"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/silphid/testchart/releases/download/v0.0.44/testchart_0.0.44_linux_amd64.tar.gz"
        sha256 "afcbd4eeaf2d6175bd5e582c6c866c1265fc5727836d7074141ae5c5a98bfa85"

        def install
          bin.install "testchart"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/silphid/testchart/releases/download/v0.0.44/testchart_0.0.44_linux_arm64.tar.gz"
        sha256 "a888e355425f6d112ff4bac958ec5e323a1372c5918af9a294085744a45885ac"

        def install
          bin.install "testchart"
        end
      end
    end
  end
end
