# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testchart < Formula
  desc "Helm chart unit testing CLI tool"
  homepage "https://github.com/silphid/tap"
  version "0.0.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silphid/testchart/releases/download/v0.0.15/testchart_0.0.15_darwin_amd64.tar.gz"
      sha256 "55a8ea99654c9a3e5c6ad2002d655e52f98827b310e1cc055242bb6849121088"

      def install
        bin.install "testchart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silphid/testchart/releases/download/v0.0.15/testchart_0.0.15_darwin_arm64.tar.gz"
      sha256 "edb296e1771068a4911918c2b4f94da8d3e0be825c86bc0f9043b6a0d6687d87"

      def install
        bin.install "testchart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/silphid/testchart/releases/download/v0.0.15/testchart_0.0.15_linux_arm64.tar.gz"
      sha256 "59d1bbedc73bc2f933d66aa8eda114cf09ba491395cae0eb5d22816162cf8d1e"

      def install
        bin.install "testchart"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/silphid/testchart/releases/download/v0.0.15/testchart_0.0.15_linux_amd64.tar.gz"
      sha256 "c7eb7bad0d1ee514c85f2a43e65f1f31519b047629010811585daeeae6804739"

      def install
        bin.install "testchart"
      end
    end
  end
end
